version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: scholarship_portal_db
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_NAME=scholarship_portal_db
      - DB_USER=portal_user
      - DB_PASSWORD=portal_password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

volumes:
  mysql_data:
